### ISSUE TITLE
Please add 0033E0C9924689 (HmIP-RGBW)

### ISSUE THREAD

**Issue by Tal1anx** [thkl/hap-homematic#668] opened 2023-12-07 20:10 UTC
**Is your feature request related to a problem? Please describe.**
I can't add the new HmIP-RGBW Module, I cant find it in the device-list. Can you add it ? 

[HmIP-RGBW.json](https://github.com/thkl/hap-homematic/files/13604675/HmIP-RGBW.json)

I would love you <3 
Thank you !

For any questions or informations to the device, don't be shy to contact me. 

With nice greetings 
Jan

**Comment by ChrWi** [comment] 2023-12-08 18:18
Duplicate of #627

**Closed by ChrWi** 2023-12-08 18:18 UTC
Labels: enhancement, DeviceService
