### ISSUE TITLE
KEQ1057311

### ISSUE THREAD

**Issue by agsenna** [thkl/hap-homematic#502] opened 2021-11-08 19:00 UTC
**Is your feature request related to a problem? Please describe.**

Note: If you just have a question or want to know something consider to open a thread in [Discussions](https://github.com/thkl/hap-homematic/discussions/new)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Device related data**
If you want to add a new device or add a feature to a new device, please login to your hap-homematic WebUI; Select Internal/Help and create the device description file as described in the dialog you will get. Please attach the file to your request.

**Comment by ChrWi** [comment] 2021-11-08 20:34
Closed as duplicate of #503

**Closed by ChrWi** 2021-11-08 20:34 UTC
Labels: enhancement, DeviceService
